TIMEZONE = "Asia/Tokyo"

SCOPES = ['https://www.googleapis.com/auth/calendar']

SYNC_STATUS_NEW = "new"
SYNC_STATUS_UPDATE = "update"
SYNC_STATUS_SYNCED = "synced"
SYNC_STATUS_DELETE = "delete"
SYNC_STATUS_NONE = "none"
SYNC_STATUS_ERROR = "error"

REPEAT_NONE = "NONE"
REPEAT_DAILY = "DAILY"
REPEAT_WEEKLY = "WEEKLY"
REPEAT_MONTHLY = "MONTHLY"

COL_ID = "id"
COL_TASK_NAME = "task_name"
COL_START_DATE = "start_date"
COL_END_DATE = "end_date"
COL_START_TIME = "start_time"
COL_END_TIME = "end_time"
COL_SYNC_STATUS = "sync_status"
COL_EVENT_ID = "eventId"
COL_REPEAT_TYPE = "repeat_type"

TASK_COLUMN_NAMES = [
  COL_ID,
  COL_TASK_NAME,
  COL_START_DATE,
  COL_END_DATE,
  COL_START_TIME,
  COL_END_TIME,
  COL_SYNC_STATUS,
  COL_EVENT_ID
]

REPEAT_TYPES = (
  REPEAT_NONE,
  REPEAT_DAILY,
  REPEAT_WEEKLY,
  REPEAT_MONTHLY
)